// Generated by CoffeeScript 1.6.3
var addCirclePoint, blue, calcCoords, center, circumference, coords70, curDeg, cx, cy, degreesPerHour, diameter, height, hours, i, radius, red, svg, toRadians, width, _i, _len;

width = 300;

height = 300;

hours = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];

red = '#ff3333';

blue = '#33cf33';

cx = width / 2;

cy = height / 2;

radius = 80;

diameter = radius * 2;

circumference = Math.PI * diameter;

calcCoords = function(cx, cy, r, a) {
  var x, y;
  x = Math.round(cx + r * Math.cos(a));
  y = Math.round(cy + r * Math.sin(a));
  return {
    x: x,
    y: y
  };
};

toRadians = function(degrees) {
  return Math.PI / 180 * degrees;
};

coords70 = calcCoords(cx, cy, radius, toRadians(70));

degreesPerHour = 360 / 12;

addCirclePoint = function(degrees) {
  var coords;
  coords = calcCoords(cx, cy, radius, toRadians(degrees));
  return svg.append('circle').style('fill', 'none').style('stroke', blue).style('stroke-width', 3).attr('cx', coords.x).attr('cy', coords.y).attr('r', 3);
};

svg = d3.select('body').append('svg').style('background', '#cccccc').attr('width', width).attr('height', height);

center = svg.append('circle').style('fill', 'none').style('stroke', blue).style('stroke-width', 3).attr('cx', cx).attr('cy', cy).attr('r', 3);

for (_i = 0, _len = hours.length; _i < _len; _i++) {
  i = hours[_i];
  curDeg = i * degreesPerHour;
  addCirclePoint(curDeg);
}
