// Generated by CoffeeScript 1.6.3
var activate, cancelActivate, cancelDeactivate, deactivate, idActivate, idDeactivate, timerActivate, timerDeactivate;

idActivate = null;

timerActivate = function() {
  var cur, log;
  cur = 0;
  log = function() {
    cur += 1;
    console.log('######## activate', cur);
    if (cur === 5) {
      clearInterval(idActivate);
      rect.on('mouseover.activate', activate);
    }
  };
  idActivate = setInterval(log, 1000);
};

activate = function() {
  rect.on('mouseover.activate', null);
  timerActivate();
};

cancelActivate = function() {
  clearInterval(idActivate);
  rect.on('mouseover.activate', activate);
};

rect.on('mouseover.activate', activate);

rect.on('mouseout.cancelActivate', cancelActivate);

idDeactivate = null;

timerDeactivate = function() {
  var cur, log;
  cur = 0;
  log = function() {
    cur += 1;
    console.log('******* deactivate', cur);
    if (cur === 5) {
      clearInterval(idDeactivate);
      return rect.on('mouseout.deactivate', deactivate);
    }
  };
  idDeactivate = setInterval(log, 1000);
};

deactivate = function() {
  rect.on('mouseout.deactivate', null);
  timerDeactivate();
};

cancelDeactivate = function() {
  clearInterval(idDeactivate);
  rect.on('mouseout.deactivate', deactivate);
};

rect.on('mouseout.deactivate', deactivate);

rect.on('mouseover.cancelDeactivate', cancelDeactivate);
