// Generated by CoffeeScript 1.6.3
var activate, cancelActivate, id, timer;

id = null;

timer = function(whatshouldhappen) {
  var cur, log;
  cur = 0;
  log = function() {
    cur += 1;
    console.log('########log', cur);
    if (cur === 5) {
      clearInterval(id);
      rect.on('mouseover', whatshouldhappen);
    }
  };
  id = setInterval(log, 1000);
};

activate = function() {
  rect.on('mouseover', null);
  timer();
};

cancelActivate = function() {
  clearInterval(id);
  rect.on('mouseover', activate);
};

rect.on('mouseover', activate);

rect.on('mouseout', cancelActivate);
